### ISSUE TITLE
gencode-mouse.symbols.tsv.gz HTTP 404

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#107]
Building a browser for a mouse dataset with ENSMUSG* IDs, I get this error:
```
INFO:root:/cluster/home/mspeir/cellbrowserData/genes/gencode-mouse.symbols.tsv.gz not found
INFO:root:Downloading https://cells.ucsc.edu/downloads/cellbrowserData/genes/gencode-mouse.symbols.tsv.gz to /cluster/home/mspeir/cellbrowserData/genes/gencode-mouse.symbols.tsv.gz...
Traceback (most recent call last):
  File "/cluster/home/mspeir/miniconda3/bin/cbBuild", line 10, in <module>
    sys.exit(cbBuildCli())
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3301, in cbBuildCli
    build(confFnames, outDir, port)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3172, in build
    convertDataset(inConf, outConf, datasetDir)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2803, in convertDataset
    geneToSym = readGeneSymbols(inConf.get("geneIdType"), inMatrixFname)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2613, in readGeneSymbols
    geneIdTable = getStaticFile(join("genes", geneIdType+".symbols.tsv.gz"))
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 235, in getStaticFile
    downloadStaticFile(relPath, absPath)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 218, in downloadStaticFile
    data = urlopen(remoteUrl).read()
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by maximilianh** [comment]
Oh this was due to to my update today, sorry! I've removed the "downloads"
link by accident. Can you try again?

**Comment by matthewspeir** [comment]
Download seems to have worked. Thanks!
