### ISSUE TITLE
0.5.37 cbImportScanpy fails at gzipped file open operation

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#117]
We have recently switched on our test to run with 0.5.37 and we get this error when using Scanpy anndata files:

```
INFO:root:Creating outdir
INFO:root:Processed matrix has size (2544 cells, 63925 genes)
INFO:root:Using raw expression matrix
INFO:root:Writing scanpy matrix (2544 cells, 63925 genes) to outdir/exprMatrix.tsv.gz
INFO:root:Transposing matrix
INFO:root:Converting csc matrix to row-sparse matrix
INFO:root:Writing gene-by-gene, without using pandas
INFO:root:Writing 63925 genes in total
INFO:root:Wrote 0 genes
INFO:root:Wrote 2000 genes
INFO:root:Wrote 4000 genes
INFO:root:Wrote 6000 genes
INFO:root:Wrote 8000 genes
INFO:root:Wrote 10000 genes
INFO:root:Wrote 12000 genes
INFO:root:Wrote 14000 genes
INFO:root:Wrote 16000 genes
INFO:root:Wrote 18000 genes
INFO:root:Wrote 20000 genes
INFO:root:Wrote 22000 genes
INFO:root:Wrote 24000 genes
INFO:root:Wrote 26000 genes
INFO:root:Wrote 28000 genes
INFO:root:Wrote 30000 genes
INFO:root:Wrote 32000 genes
INFO:root:Wrote 34000 genes
INFO:root:Wrote 36000 genes
INFO:root:Wrote 38000 genes
INFO:root:Wrote 40000 genes
INFO:root:Wrote 42000 genes
INFO:root:Wrote 44000 genes
INFO:root:Wrote 46000 genes
INFO:root:Wrote 48000 genes
INFO:root:Wrote 50000 genes
INFO:root:Wrote 52000 genes
INFO:root:Wrote 54000 genes
INFO:root:Wrote 56000 genes
INFO:root:Wrote 58000 genes
INFO:root:Wrote 60000 genes
INFO:root:Wrote 62000 genes
INFO:root:Writing t-SNE coords to outdir/tsne_coords.tsv
INFO:root:Writing UMAP coords to outdir/umap_coords.tsv
INFO:root:Writing outdir/markers.tsv
INFO:root:Wrote outdir/cellbrowser.conf
INFO:root:Wrote outdir/summary.html
INFO:root:Wrote outdir/downloads.html
INFO:root:Creating /export/galaxy-central/database/job_working_directory/000/442/dataset_719_files/sample
INFO:root:Creating /export/galaxy-central/database/job_working_directory/000/442/dataset_719_files/sample/metaFields
INFO:root:Checking and reordering meta data to /export/galaxy-central/database/job_working_directory/000/442/dataset_719_files/sample/meta.tsv
INFO:root:Reading sample names from /export/database/job_working_directory/000/442/working/outdir/meta.tsv
INFO:root:Reading headers of file /export/database/job_working_directory/000/442/working/outdir/exprMatrix.tsv.gz
Traceback (most recent call last):
  File "/usr/local/bin/cbImportScanpy", line 12, in <module>
    sys.exit(cbImportScanpyCli())
  File "/usr/local/lib/python3.7/site-packages/cellbrowser/convert.py", line 527, in cbImportScanpyCli
    build(outDir, options.htmlDir, port=options.port)
  File "/usr/local/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 3361, in build
    convertDataset(inConf, outConf, datasetDir)
  File "/usr/local/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 2960, in convertDataset
    sampleNames, needFilterMatrix, outMeta = convertMeta(inConf, outConf, datasetDir)
  File "/usr/local/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 2728, in convertMeta
    sampleNames, needFilterMatrix = metaReorder(matrixFname, metaFname, finalMetaFname)
  File "/usr/local/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 1797, in metaReorder
    matrixSampleNames = readHeaders(matrixFname)[1:]
  File "/usr/local/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 2430, in readHeaders
    ifh = openFile(fname, "rtU")
  File "/usr/local/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 596, in openFile
    fh = gzip.open(fname, mode, encoding="latin1")
  File "/usr/local/lib/python3.7/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/local/lib/python3.7/gzip.py", line 159, in __init__
    raise ValueError("Invalid mode: {!r}".format(mode))
```

**Comment by maximilianh** [comment]
Oops. I’ve already fixed this but it may have been after the last
release....

**Comment by pcm32** [comment]
Could you then a new release with that? Then we can grab it on bioconda and on our Galaxy module (which by the way you can now use at https://humancellatlas.usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Febi-gxa%2Fucsc_cell_browser%2Fucsc_cell_browser%2F0.5.21%2Bgalaxy0)

**Comment by maximilianh** [comment]
This should be solved now.
