### ISSUE TITLE
[0.5.38] Missing tiny-queue.js file on conda installation make `cbImportScanpy` fail

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#123]
On running `cbImportScanpy` I get the following failure due to missing tiny-queue.js file in the ext folder (there are other files in there that are getting installed correctly):

```python
Traceback (most recent call last):
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.5.38/bin/cbImportScanpy", line 12, in <module>
    sys.exit(cbImportScanpyCli())
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.5.38/lib/python3.7/site-packages/cellbrowser/convert.py", line 529, in cbImportScanpyCli
    build(outDir, options.htmlDir, port=options.port)
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.5.38/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 3465, in build
    cbUpgrade(outDir, datasets)
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.5.38/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 4084, in cbUpgrade
    makeIndexHtml(webDir, datasets, outDir, devMode=devMode)
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.5.38/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 4032, in makeIndexHtml
    writeVersionedLink(ofh, '<script src="%s"></script>', baseDir, jsFname, addVersion=addVersion)
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.5.38/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 3916, in writeVersionedLink
    md5 = md5WithPython(filePath)
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.5.38/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 2906, in md5WithPython
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.5.38/lib/python3.7/site-packages/cellbrowser/cbWeb/ext/tiny-queue.js' 
```

Files currently available on a fresh install are on ext are:

```bash
Chart.bundle.min.js			introjs.2.4.0.min.css			papaparse.min.js
FastBitSet.js				jquery-ui-1.12.1.css			select2.4.0.4.min.css
FileSaver.1.1.20151003.min.js		jquery-ui.min.js			select2.min.js
OverlayScrollbars.min.css		jquery.3.1.1.min.js			selectize.bootstrap3.css
bootstrap-dropmenu.min.css		jquery.contextMenu.css			selectize.js
bootstrap-submenu.js			jquery.contextMenu.js			slick.cellrangedecorator.js
bootstrap-submenu.min.css		jquery.event.drag-2.3.0.js		slick.cellrangeselector.js
bootstrap.3.3.7.min.css			jquery.overlayScrollbars.min.js		slick.cellselectionmodel.js
bootstrap.min.css			jquery.sparkline.min.js			slick.core.js
bootstrap.min.js			jquery.tipsy.1.0.3.min.css		slick.editors.js
chartjs-chart-box-and-violin-plot.js	jquery.tipsy.min.js			slick.examples.css
chosen-sprite.png			jquery.ui.position.min.js		slick.formatters.js
chosen.1.8.2.min.css			jsurl2.js				slick.grid.css
chosen.jquery.min.js			lz-string.js				slick.grid.js
font-awesome.css			materialIcons.woff			spectrum-1.8.0.css
googleMaterialIcons.css			mousetrap.min.js			spectrum.min.js
hamster.js				normalizeWheel.js			split.js
images					pako_inflate.min.js			tablesort.js
intro.min.js				palette.js				tablesort.number.min.js
```

**Comment by pcm32** [comment]
I guess this is because the file is not present in `https://github.com/maximilianh/cellBrowser/tree/master/src/cbPyLib/cellbrowser/cbWeb/ext`.

**Comment by maximilianh** [comment]
Oh oh, darn, my mistake, sorry, will fix this immediately.

**Comment by maximilianh** [comment]
ok, I've released 0.5.41 now, sorry for such a stupid bug! Something like
this should not happen, but even CI wouldn't really help. I just need to be
more careful with my commits.

**Comment by pcm32** [comment]
Thanks @maximilianh. I switched the bioconda package to install from the pip hosted file instead of github, as you seem to release more often there, but installation fails because https://github.com/maximilianh/cellBrowser/blob/master/LICENSE doesn't get included in the pip package:

```
13:21:24 BIOCONDA INFO (OUT) ValueError: License file given in about/license_file (/opt/recipe/LICENSE) does not exist in source root dir or in recipe root dir (with meta.yaml)
13:21:26 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmp0f2b3v1s/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld/:/opt/host-conda-bld -v /Users/pmoreno/Development/bioconda-recipes/recipes/ucsc-cell-browser:/opt/recipe -e LANG=en_GB.UTF-8 -e HOST_USER_ID=502 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash
```

Could you either add the LICENSE to the pip package and re-release 0.5.41 or make a release on github? If you fix the pip one, then I won't bother you anymore with github releases ;-).

**Comment by maximilianh** [comment]
Ah, weird that this is suddenly a problem but used to work just fine until
now. I had no idea conda requires this file. Sure, I've added the file now,
can you try 0.5.42 ?

>

**Comment by pcm32** [comment]
Thanks for fixing this @maximilianh, please see issue #124 with other problems I get with the newest version.
