### ISSUE TITLE
[0.5.42] cbImportScanpy fails with unrecognised htmlDir issue

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#124]
After doing:

```bash
python3 -m venv cellbrowser-venv
source cellbrowser-venv/bin/activate
pip install cellbrowser
```

trying:

```bash
cbImportScanpy -i scanpy_ann_data.h5ad -o /tmp/cell_browser_test/outdir -n sample --htmlDir /tmp/cell_browser_test/html
```

fails with:

```python
Traceback (most recent call last):
  File "/private/tmp/cell_browser_test/cellbrowser-venv/bin/cbImportScanpy", line 11, in <module>
    load_entry_point('cellbrowser==0.5.42', 'console_scripts', 'cbImportScanpy')()
  File "/private/tmp/cell_browser_test/cellbrowser-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/private/tmp/cell_browser_test/cellbrowser-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/private/tmp/cell_browser_test/cellbrowser-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/private/tmp/cell_browser_test/cellbrowser-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/private/tmp/cell_browser_test/cellbrowser-venv/lib/python3.6/site-packages/cellbrowser/convert.py", line 7, in <module>
    from .cellbrowser import runGzip, openFile, errAbort, setDebug, moveOrGzip, makeDir, iterItems
  File "/private/tmp/cell_browser_test/cellbrowser-venv/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 353, in <module>
    defOutDir = expanduser(getConfig("htmlDir"))
  File "/usr/local/bin/../Cellar/python/3.6.5_1/bin/../Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The same happens on a conda based installation :-(

Both `html` and `outdir` exist in the path proposed.

**Comment by maximilianh** [comment]
Oh. You don't have these set... yes, I should tolerate that. One sec...

**Comment by maximilianh** [comment]
OK, 0.5.43 fixes this. In all my tests, I always set this variable, but of
course it shouldn't be required. Thanks for finding this!

>
