### ISSUE TITLE
Error on importing h5ad file with cbImportScanpy

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#125]
When I try importing one of the new Tabula Muris Senis h5ad files, I get the following error:
```
INFO:root:Writing UMAP coords to tms-brain-myeloid-facs/umap_coords.tsv
Traceback (most recent call last):
  File "/cluster/home/mspeir/miniconda3/bin/cbImportScanpy", line 10, in <module>
    sys.exit(cbImportScanpyCli())
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/convert.py", line 522, in cbImportScanpyCli
    markerField=markerField)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3278, in scanpyToCellbrowser
    writeAnndataCoords(adata, layoutCode, path, layoutCode, layoutName, coordDescs)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3098, in writeAnndataCoords
    fa2_coord.columns=['x','y']
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 4385, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 645, in _set_axis
    self._data.set_axis(axis, labels)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 3323, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 12 elements, new values have 2 elements
```
Some files (e.g. Bladder_droplet.h5ad and Bladder_facs.h5ad) work fine, but running it for this dataset (Brain_Myeloid_facs.h5ad) results in an error.

Command:
```
cbImportScanpy -i orig/Brain_Myeloid_facs.h5ad -o tms-brain-myeloid-facs -n tms-brain-myeloid-facs
```
Data location:
```
/hive/data/inside/cells/datasets/tabula-muris-senis
```

**Comment by maximilianh** [comment]
Ah. This happens when the object contains more than two dimensions. In this
case, they calculated umap with many dimensions. Apparently only for a few
tissues. Fixed now in 0.5.45.
Thanks!
