### ISSUE TITLE
cbUpgrade errors (0.5.49 -> current develop branch)

### ISSUE THREAD

**Issue by ljpearlman** [maximilianh/cellBrowser#153]
I'd previously installed 0.5.49, and when trying to upgrade, I got this:

```
cbUpgrade --code -o /var/www/html/demo/cellbrowser
INFO:root:dataRoot is not set in ~/.cellbrowser.conf. Dataset hierarchies are not supported.
INFO:root:Not using dataset hierarchies: no need to rebuild dataset list
INFO:root:Copying js, css and img files to /var/www/html/demo/cellbrowser
Traceback (most recent call last):
  File "/home/laura/.conda/envs/cellbrowser/bin/cbUpgrade", line 11, in <module>
    load_entry_point('cellbrowser==0.7.1.post0.dev22', 'console_scripts', 'cbUpgrade')()
  File "/home/laura/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-0.7.1.post0.dev22-py3.8.egg/cellbrowser/cellbrowser.py", line 4789, in cbUpgradeCli
    cbUpgrade(outDir, doCode=options.addCode, devMode=options.devMode, port=options.port)
  File "/home/laura/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-0.7.1.post0.dev22-py3.8.egg/cellbrowser/cellbrowser.py", line 4773, in cbUpgrade
    makeIndexHtml(webDir, outDir, devMode=devMode)
  File "/home/laura/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-0.7.1.post0.dev22-py3.8.egg/cellbrowser/cellbrowser.py", line 4718, in makeIndexHtml
    md5 = md5WithPython(join(outDir, "dataset.json"))
  File "/home/laura/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-0.7.1.post0.dev22-py3.8.egg/cellbrowser/cellbrowser.py", line 3324, in md5WithPython
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/html/demo/cellbrowser/dataset.json'
```

Also, there's a typo in the help output for cbUpgrade:
```
Usage: cbUpgrade [options] outDir - update the list of datasets in the output directory, optionally updating the javascript code
```

but the output directory is specified with the `-o` option (which is documented later in the help), not as a positional argument.

**Comment by maximilianh** [comment]
Thanks for the typo!

But are you sure that you have run cbBuild before to convert this dataset ?
cbUpgrade does not convert, it only updates the dataset.json files...

**Comment by maximilianh** [comment]
Hi @ljpearlman, just wondering if I've misunderstood something. But it
looks to me like the dataset.json is not there, which suggests that
the dataset was never built.

It may be confusing, but right now we have two different commands:
cbBuild, to build the dataset to the output directory and which is
documented quite a bit. And cbUpgrade, which we have documented only
in the context of dataset hierarchies. chUpgrade recreates the dataset
structure, the dataset.json files, but they have to exist already.
There is also cbUpgrade --code which we haven't documented at all and
only tell people who need to upgrade their code.

(cbUpgrade was changed recently to not automatically upgrade the code
anymore, to avoid that someone accidentally overwrites their own code
that they need. Now the tool name makes a little bit less sense and we
could rename the tool to something that better reflects the fact that
it links datasets together by default....)

**Comment by ljpearlman** [comment]
There are dataset.json files for the individual datasets, but it seems to be looking for a top-level dataset.json file.

```
rbk-staging::laura[~] ls /var/www/html/demo/cellbrowser/
16-2D54  16-2D5A  css  ext  img  index.html  index.html.tmp  js
rbk-staging::laura[~] ls /var/www/html/demo/cellbrowser/16-2D5A
16-2D5A.thumb.png     desc.json        exprMatrix.json    meta.index
cellbrowser.json.bak  discretMat.bin   exprMatrix.tsv.gz  meta.tsv
coords                discretMat.json  markers            Seurat_pca.coords.tsv.gz
dataset.json          exprMatrix.bin   metaFields         Seurat_tsne.coords.tsv.gz
```

cbupgrade -code gives me a similar error:
```
(cellbrowser) rbk-staging::laura[~] cbUpgrade --code -o /var/www/html/demo/cellbrowser
INFO:root:dataRoot is not set in ~/.cellbrowser.conf. Dataset hierarchies are not supported.
INFO:root:Not using dataset hierarchies: no need to rebuild dataset list
INFO:root:Copying js, css and img files to /var/www/html/demo/cellbrowser
Traceback (most recent call last):
  File "/home/laura/.conda/envs/cellbrowser/bin/cbUpgrade", line 11, in <module>
    load_entry_point('cellbrowser==0.7.1.post0.dev22', 'console_scripts', 'cbUpgrade')()
  File "/home/laura/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-0.7.1.post0.dev22-py3.8.egg/cellbrowser/cellbrowser.py", line 4789, in cbUpgradeCli
    cbUpgrade(outDir, doCode=options.addCode, devMode=options.devMode, port=options.port)
  File "/home/laura/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-0.7.1.post0.dev22-py3.8.egg/cellbrowser/cellbrowser.py", line 4773, in cbUpgrade
    makeIndexHtml(webDir, outDir, devMode=devMode)
  File "/home/laura/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-0.7.1.post0.dev22-py3.8.egg/cellbrowser/cellbrowser.py", line 4718, in makeIndexHtml
    md5 = md5WithPython(join(outDir, "dataset.json"))
  File "/home/laura/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-0.7.1.post0.dev22-py3.8.egg/cellbrowser/cellbrowser.py", line 3324, in md5WithPython
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/html/demo/cellbrowser/dataset.json'
```

**Comment by matthewspeir** [comment]
Hi, @ljpearlman! Just going through some old issues. I apologize for not getting back to you. Is this still a problem?
