### ISSUE TITLE
Another silent error (failure with no error code)

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#213]
I found that this error:

```
INFO:root:Filtering for >5 cells then do sc.tl.rank_genes_groups for meta field 'cell_type'
Traceback (most recent call last):
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@1.0.0/bin/cbImportScanpy", line 10, in <module>
    sys.exit(cbImportScanpyCli())
  File "/Users/pmoreno/miniconda/envs/__ucsc-cell-browser@1.0.0/lib/python3.9/site-packages/cellbrowser/convert.py", line 600, in cbImportScanpyCli
    scanpyToCellbrowser(ad, outDir, datasetName, skipMatrix=options.skipMatrix, useRaw=(not options.useProc),
  File "/Users/pmoreno/miniconda/envs/__ucsc-cell-browser@1.0.0/lib/python3.9/site-packages/cellbrowser/cellbrowser.py", line 4271, in scanpyToCellbrowser
    adata = runSafeRankGenesGroups(adata, clusterField, minCells=5)
  File "/Users/pmoreno/miniconda/envs/__ucsc-cell-browser@1.0.0/lib/python3.9/site-packages/cellbrowser/cellbrowser.py", line 4157, in runSafeRankGenesGroups
    import scanpy as sc
ModuleNotFoundError: No module named 'scanpy'
```

doesn't produce an exit with an error code (>0). This makes Galaxy and any wf environment dizzy.

**Comment by maximilianh** [comment]
Thanks!  fixed now in the develop branch.
