### ISSUE TITLE
Sample Dataset TypeError: 'NoneType'

### ISSUE THREAD

**Issue by apblair** [maximilianh/cellBrowser#22]
Running into an error when attempting to build a viewer with sample dataset in sampleData/sample1.

`Traceback (most recent call last):
  File "../../src/cbBuild", line 10, in <module>
    cellbrowser.convertAndCopyCli()
  File "../../src/cbPyLib/cellbrowser.py", line 2145, in convertAndCopyCli
    convertAndCopy(confFnames, outDir, port)
  File "../../src/cbPyLib/cellbrowser.py", line 2119, in convertAndCopy
    convertDataset(inConf, outConf, datasetDir)
  File "../../src/cbPyLib/cellbrowser.py", line 1962, in convertDataset
    convertExprMatrix(inConf, outMatrixFname, outConf, sampleNames, geneToSym, datasetDir, needFilterMatrix)
  File "../../src/cbPyLib/cellbrowser.py", line 1696, in convertExprMatrix
    matType = matrixToBin(outMatrixFname, geneToSym, binMat, binMatIndex, discretBinMat, discretMatrixIndex)
  File "../../src/cbPyLib/cellbrowser.py", line 1035, in matrixToBin
    matType, sampleNames = matReader.open(fname)
TypeError: 'NoneType' object is not iterable`

**Comment by apblair** [comment]
After the second git pull I am also receiving an error that the output file dataset.json is broken. I will email you the dataset.json file but also posting the contents here for future reference.

{
  "desc": {
    "summary": "summary.html",
    "methods": "methods.html",
    "downloads": "downloads.html"
  },
  "name": "sample",
  "shortLabel": "CellBrowser 100-genes demo",
  "radius": 5,
  "alpha": 0.3,
  "priority": 10,
  "tags": [
    "smartseq2"
  ],
  "clusterField": "WGCNAcluster",
  "hubUrl": "http://cells.ucsc.edu/cortex-dev/hub/hub.txt",
  "showLabels": true,
  "ucscDb": "hg38",
  "fileVersions": {
    "inMeta": {
      "fname": "/projects/sysbio/users/apblair/single_cell/cellBrowser/sampleData/sample1/meta.tsv",
      "md5":

**Comment by maximilianh** [comment]
Yes, weird. This file is clearly truncated. The only explanation for this
situation that I can see is that you did ctrl+c while the script was
running...

I'll change it so this can't happen anymore.

And yes, there is still an error message, but the new error message
suggested that you remove the file and restart the script. Could you try
that?

**Comment by apblair** [comment]
I very well might have hit ctrl+c at one point while running the script. I removed the dataset.json from ~/cells and did another git pull but I'm running into a JSON serializable error now:

Traceback (most recent call last):
  File "../../src/cbBuild", line 10, in <module>
    cellbrowser.convertAndCopyCli()
  File "../../src/cbPyLib/cellbrowser.py", line 2252, in convertAndCopyCli
    convertAndCopy(confFnames, outDir, port)
  File "../../src/cbPyLib/cellbrowser.py", line 2226, in convertAndCopy
    convertDataset(inConf, outConf, datasetDir)
  File "../../src/cbPyLib/cellbrowser.py", line 2066, in convertDataset
    writeConfig(inConf, outConf, datasetDir)
  File "../../src/cbPyLib/cellbrowser.py", line 2183, in writeConfig
    json.dump(outConf, descJsonFh, indent=2)
  File "/soe/apblair/anaconda3/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/soe/apblair/anaconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/soe/apblair/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/soe/apblair/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/soe/apblair/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/soe/apblair/anaconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/soe/apblair/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

**Comment by maximilianh** [comment]
Oh! Now I understand! You're running this on python3! Sorry!
(btw: what is your platform? I'm surprised that your platform uses python3
as the default python...)

Once I figured out that it's on python 3 (thanks for sending the full error
message this time, it was very easy to fix. Can you try again?

**Comment by apblair** [comment]
I'm working on the stuart lab server (tap), which I believe is managed by BSOE, and the platform is CentOS 7.5.1804 release. I installed anaconda and upgraded to python 3.5. But it looks like it works now https://users.soe.ucsc.edu/~apblair/  

Thanks again for your help :+1:
