### ISSUE TITLE
KeyError: 'name' during cbImportSeurat 

### ISSUE THREAD

**Issue by malcook** [maximilianh/cellBrowser#268]
cbImportSeurat is failing with
```
Prepared cellbrowser directory anchored_Nmast_sub_anchored_seurat3_v1.0
Warning messages:
1: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 2.2 GiB
2: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 2.2 GiB
3: In ExportToCellbrowser(sobj, "anchored_Nmast_sub_anchored_seurat3_v1.0",  :
  Embedding pca has more than 2 coordinates, taking only the first 2

real	21m23.629s
user	21m5.568s
sys	0m19.625s
INFO:root:Wrote logfile of R run to anchored_Nmast_sub_anchored_seurat3_v1.0/analysisLog.txt
INFO:root:identical and same size, not copying /n/projects/nt2473/Analysis/Data/sb2191-regen/SeurObj_anchored_Nmast_sub_anchored_seurat3_v1.0_.RDS to anchored_Nmast_sub_anchored_seurat3_v1.0/SeurObj_anchored_Nmast_sub_anchored_seurat3_v1.0_.RDS
INFO:root:Not writing anchored_Nmast_sub_anchored_seurat3_v1.0/desc.conf, already exists
WARNING:root:The directory ./sb2191-regen does not exist. Making a new directory now.
INFO:root:dataRoot is not set in ~/.cellbrowser or via $CBDATAROOT. Dataset hierarchies are not supported.
Traceback (most recent call last):
  File "/n/projects/mec/SRSCHPC2/local/inst/Mambaforge/24.3.0-0/envs/ucsc-cell-browser/bin/cbImportSeurat", line 10, in <module>
    sys.exit(cbImportSeuratCli())
  File "/n/projects/mec/SRSCHPC2/local/inst/Mambaforge/24.3.0-0/envs/ucsc-cell-browser/lib/python3.9/site-packages/cellbrowser/seurat.py", line 567, in cbImportSeuratCli
    build(outDir, options.htmlDir, port=options.port)
  File "/n/projects/mec/SRSCHPC2/local/inst/Mambaforge/24.3.0-0/envs/ucsc-cell-browser/lib/python3.9/site-packages/cellbrowser/cellbrowser.py", line 5575, in build
    dataRoot, relPath, inConf, dsName = fixupName(inConfFname, inConf)
  File "/n/projects/mec/SRSCHPC2/local/inst/Mambaforge/24.3.0-0/envs/ucsc-cell-browser/lib/python3.9/site-packages/cellbrowser/cellbrowser.py", line 5490, in fixupName
    relPath = inConf["name"]
KeyError: 'name'
```

using a fresh install of cellBrowser 

what more diagnostics can I provide

FWIW installing the sample from `https://cells.ucsc.edu/downloads/samples/mini.tgz ` works perfectly

**Comment by maximilianh** [comment]
Hi Malcolm,

great to hear from you! Can you tell me how you created this
cellbrowser.conf file?

I added this error message now, I hope this explains why the name setting
is required:

+        if not "name" in inConf:
+            errAbort("Not running in data hierarchy mode. "
+                "The config file %s needs at least the setting 'name' to a
short string, e.g. 'cortex-dev'. "
+                "If you set  a dataRoot directory in your ~/.cellbrowser
file or via the CBDATAROOT variable, then the input datasets "
+                "are assumed to be under one single directory and their
subdirectory name is the datasetname. "
+                "Otherwise, as now, they can be spread out over the entire
filesystem but then the directory name cannot be used to "
+                "derive the cell browser dataset name. Instead, a 'name'
setting must be present in every cellbrowser.conf file." % inConfName)

see:
 https://cellbrowser.readthedocs.io/en/develop/collections.html

Let us know if you have any other error messages or suggestions! Especially
UI suggestions... This UI is not an easy one...

**Comment by malcook** [comment]
Hi Maximilian,

I am trying to resurrect old cb site and think I’d better just start over.

That said, I’m having a little trouble understanding dataset hierarchy.

To demonstrate my confusion, here I try to install sample data twice:

conda activate ucsc-cell-browser
module load R/4.4.0
export CBDATAROOT=~/public_html/cellbrowser
mkdir -p  ${CBDATAROOT}
cd ${CBDATAROOT}
printf 'title = "my title"
description="my description"
' > desc.conf
printf 'shortLabel="some description"
' > cellbrowser.conf
pushd /tmp
curl -O -ks https://cells.ucsc.edu/downloads/samples/mini.tgz
tar -zxv -f mini.tgz
cd mini
cbBuild -o ${CBDATAROOT}/mini1
cbBuild -o ${CBDATAROOT}/mini2


I know this is wrong but this is how I read your instructions.

I can browse to http://myserver/~me/cellbrowser/mini1 and http://myserver/~me/cellbrowser/mini2 but they are independent sites and browsing to http://myserver/~me/cellbrowser<http://myserver/~me/cellbrowser/mini1> just displays directory (as I would expect).

What am I missing?  Clearly something fundamental!

Thanks!

~ ***@***.***

**Comment by maximilianh** [comment]
The -o option specifies the htdocs directory with your html files. Where in
the docs should I explain this better ? Someone else here has the same
problem. I probably should make this clearer somehow …

CBDATAROOT is where the input files are stored it has little  to do with
the final html output files. The files get converted from
CBDATAROOT/datasetName to htmlDirectory/datasetName.

**Comment by malcook** [comment]
Hi again!

I’m still not understanding.

One source of my confusion is the following:

First, you write
Add a statement like the following to your ~/.cellbrowser.conf: …
                            dataRoot='/celldata/'

Then later you write
              Then, create a “stub” cellbrowser.conf into this directory, it should only contain a single line like shortLabel="some description".

This confuses me.  How many cellbrowers.conf files are we talking about here?  Only one?

Another source of confusion for me is that `cbBuild` takes its default value for`-o` from `CBOUT` whereas `cbImportSeurat` does not take a default for `-o`.

Q: Do I understand correctly that, the -o option to cbBuild is an htmlDir whereas the -o option to ` cbImportSeurat` is a data directory?

If so, then do you agree that if I am calling `cbImportSeurat -i /path/to/my_wellnamed_experiment.rds` then a reasonable value of -o is might be “${CBDATAROOT}/my_wellnamed_experiment”?

Perhaps your documentation could benefit from an example wherein you go from absolutely nothing to having a cellbrowser configured with multiple datasets arranged in a hierarchy.  The example might:

  *   Use environment variables (CBDATAROOT, CBOUT)  throughout
  *   illustrate deploying  https://cells.ucsc.edu/downloads/samples/mini.tgz<https://cells.ucsc.edu/downloads/samples/mini.tgz>
  *   illustrate command-line deploying in a different manner (e.g. using cbImportSeurat)


I took another pass at doing this and maybe got further but still have an error executing the last line (the second cbBuild) when running


export CB=~/public_html/cellbrowser
export CBOUT=${CB}/www
export CBDATAROOT=${CB}/data
mkdir -p ${CBOUT} ${CBDATAROOT}
cd  ${CBDATAROOT}
printf 'shortLabel="some description"' > cellbrowser.conf
cd ${CBDATAROOT}
curl -O -ks https://cells.ucsc.edu/downloads/samples/mini.tgz
tar -zxv -f mini.tgz
cd mini
cbBuild
i='/n/projects/nt2473/Analysis/Data/sb2191-regen/SeurObj_anchored_Nmast_sub_anchored_seurat3_v1.0_.RDS'
b=$(basename ${i} _.RDS)
cbImportSeurat -i ${i} -o ${CBDATAROOT}/${b}
cd ${CBDATAROOT}/${b}
cbBuild


The error is:

INFO:root:input directory cellbrowser.conf is not located under dataRoot /home/mec/public_html/cellbrowser/data. Deactivating hierarchies.
(<class 'KeyError'>, KeyError('name'), <traceback object at 0x7fb81a2105c0>)
<class 'type'>
<class 'KeyError'>
ERROR:root:Unexpected error: (<class 'KeyError'>, KeyError('name'), <traceback object at 0x7fb81a2105c0>)
Traceback (most recent call last):
  File "/n/projects/mec/SRSCHPC2/local/inst/Mambaforge/24.3.0-0/envs/ucsc-cell-browser/lib/python3.9/site-packages/cellbrowser/cellbrowser.py", line 5775, in cbBuildCli
    build(confFnames, outDir, port, redo=options.redo)
  File "/n/projects/mec/SRSCHPC2/local/inst/Mambaforge/24.3.0-0/envs/ucsc-cell-browser/lib/python3.9/site-packages/cellbrowser/cellbrowser.py", line 5575, in build
    dataRoot, relPath, inConf, dsName = fixupName(inConfFname, inConf)
  File "/n/projects/mec/SRSCHPC2/local/inst/Mambaforge/24.3.0-0/envs/ucsc-cell-browser/lib/python3.9/site-packages/cellbrowser/cellbrowser.py", line 5490, in fixupName
    relPath = inConf["name"]
KeyError: 'name'

Which confuses me since is appears to me that the conf file is within the dataRoot directory

(ucsc-cell-browser) ***@***.***:$ pwd
/home/mec/public_html/cellbrowser/data/SeurObj_anchored_Nmast_sub_anchored_seurat3_v1.0
(ucsc-cell-browser) ***@***.***:$ ls -lah
total 3.4G
drwxrwx---. 2 mec domain users   437 Sep 25 10:19 .
drwxrwxr-x. 4 mec domain users   148 Sep 25 10:19 ..
-rw-r-----. 1 mec domain users  3.2G Sep 25 09:47 SeurObj_anchored_Nmast_sub_anchored_seurat3_v1.0_.RDS
-rw-r-----. 1 mec domain users  5.8K Sep 25 09:46 analysisLog.txt
-rw-r-----. 1 mec domain users     0 Sep 25 09:46 cellbrowser.conf
-rw-r-----. 1 mec domain users   17M Sep 25 09:35 counts_exprMatrix.tsv.gz
-rw-r-----. 1 mec domain users  112M Sep 25 09:40 data_exprMatrix.tsv.gz
-rw-r-----. 1 mec domain users  2.7K Sep 25 09:47 desc.conf
-rw-r-----. 1 mec domain users   68K Sep 25 09:46 markers.tsv
-rw-r-----. 1 mec domain users  1.8M Sep 25 09:46 meta.tsv
-rw-r-----. 1 mec domain users  997K Sep 25 09:46 pca.coords.tsv
-rw-r-----. 1 mec domain users   22K Sep 25 09:30 runSeurat.R
-rw-r-----. 1 mec domain users  142M Sep 25 09:46 scale_exprMatrix.tsv.gz
-rw-r-----. 1 mec domain users 1010K Sep 25 09:46 umap.coords.tsv

Sorry to ask you to wade through all this.  Is there a better set of diagnostics I should provide?

Finally,

Q: you write “Make sure that you have the same major version of Seurat installed that was used to create the object. You cannot open Seurat2 objects with Seurat3 or vice versa.”   But my log seems to say this is OK:

              SeuratVersion installed = 5.1.00
ObjectVersion Seurat object was created with Seurat version = 3.1.0
The installed major version of Seurat is different from Seurat input object. Running the UpdateSeuratObject() function now

Is this no longer a concern so long as after doing this

              Object representation is consistent with the most current Seurat version

Cheers,

~ ***@***.***

**Comment by maximilianh** [comment]
>
>
> First, you write
> Add a statement like the following to your ~/.cellbrowser.conf: …
> dataRoot='/celldata/'


This defines the root directory under which all future cell browser data
files will be located. Does this help?

Then later you write
> Then, create a “stub” cellbrowser.conf into this directory, it should only
> contain a single line like shortLabel="some description".


This is only a stub to make sure that the root directory has a label.

This confuses me. How many cellbrowers.conf files are we talking about
> here? Only one?

So far, no single dataset has been defined. Only the root directory has
been set. Does this help? (I'm asking so I can improve the documentation)

Another source of confusion for me is that `cbBuild` takes its default
> value for`-o` from `CBOUT` whereas `cbImportSeurat` does not take a default
> for `-o`.

cbBuild outputs html files. cbImportSeurat outputs .tsv files and a matrix
file and config files for cbBuild. The output of cbImportSeurat is the
input for cbBuild.

Q: Do I understand correctly that, the -o option to cbBuild is an htmlDir
> whereas the -o option to ` cbImportSeurat` is a data directory?

YES! I don't think I can still change the letters of these options, but I
can change the usage messages and the documentation html pages.


> If so, then do you agree that if I am calling `cbImportSeurat -i
> /path/to/my_wellnamed_experiment.rds` then a reasonable value of -o is
> might be “${CBDATAROOT}/my_wellnamed_experiment”?

YES!

Perhaps your documentation could benefit from an example wherein you go
> from absolutely nothing to having a cellbrowser configured with multiple
> datasets arranged in a hierarchy. The example might:
> * Use environment variables (CBDATAROOT, CBOUT) throughout
> * illustrate deploying https://cells.ucsc.edu/downloads/samples/mini.tgz<
> https://cells.ucsc.edu/downloads/samples/mini.tgz>
> * illustrate command-line deploying in a different manner (e.g. using
> cbImportSeurat)

Thanks!


> INFO:root:input directory cellbrowser.conf is not located under dataRoot
> /home/mec/public_html/cellbrowser/data. Deactivating hierarchies.
>

I see... I wonder if public_html is a symlink or some sort of linkin is
going on there in the file system. To find out if cellbrowser.conf is
located under the dataRoot, it's trying if abspath(indir) starts with
dataRoot, like this, in cellbrowser.py:findRoot()

    if inDir is not None and not abspath(inDir).startswith(dataRoot):
        logging.info("input directory %s is not located under dataRoot %s.
Deactivating hierarchies." % (inDir, dataRoot))
        return None

Not sure how this can fail here.

I've improved this error message, it should now output the full input
directory, rather than just the filename of cellbrowser.conf, can you do a
git pull and retry the same command? Thanks! The new error message will
output both directories, not just one.

Which confuses me since is appears to me that the conf file is within the
> dataRoot directory

Yes. It is confusing me, too.

>
> Sorry to ask you to wade through all this. Is there a better set of
> diagnostics I should provide?

This is awesome.

>
> Is this no longer a concern so long as after doing this

This is solved! Seurat can import anything now. Updated the docs.

**Comment by malcook** [comment]
public_html was a symlink!  I made it hoping it would make my example easier to follow.  Alas, it exposed a different issue.  Hah! Playing whack-a-mole with myself.

I will try again next Monday.

Taking a holiday tomorrow.  Have a great weekend.

~ ***@***.***

**Comment by maximilianh** [comment]
Nice, so that may explain it. But, according to
https://stackoverflow.com/questions/37863476/why-would-one-use-both-os-path-abspath-and-os-path-realpath,
abspath doesn't resolve symlinks, so now I'm confused. I'm not using
realpath(), which would resolve the symlink...hmmm. If you use git and you
can do a git pull and use the master branch of cbBuild, we will know more
on Monday. Happy weekend!
