### ISSUE TITLE
cbScanpy --init doesn't exist

### ISSUE THREAD

**Issue by Jeltje** [maximilianh/cellBrowser#44]
```
cbScanpy --init
Usage: cbScanpy [options] -e matrixFile -o outDir - run scanpy and output .tsv files
    If exceptions occur, will automatically start the debugger.
cbScanpy: error: no such option: --init
```
Version:
```
pip list | grep cell
cellbrowser      0.4.4
```
Usage statement
```
cbScanpy -h
Usage: cbScanpy [options] -e matrixFile -o outDir - run scanpy and output .tsv files

    If exceptions occur, will automatically start the debugger.


Options:
  -h, --help            show this help message and exit
  -e EXPRMATRIX, --exprMatrix=EXPRMATRIX
                        gene-cell expression matrix file, possible formats:
                        .h5ad, .csv, .xlsx, .h5, .loom, .mtx, .txt, .tab,
                        .data
  -o OUTDIR, --outDir=OUTDIR
                        output directory
  -c CONFFNAME, --confFname=CONFFNAME
                        config file from which settings are read, default is
                        scanpy.conf
  -s, --samplesOnRows   when reading the expression matrix from a text file,
                        assume that samples are on lines (default behavior is
                        one-gene-per-line, one-sample-per-column)
  -n NAME, --name=NAME  name of dataset in cell browser, default cbScanpy-Data
  --test                run doctests
  -d, --debug           open an iPython shell when an exception occurs. also
                        output debug messages
```

**Comment by Jeltje** [comment]
I do notice `scanpy.conf` comes with the example so maybe that statement in the README is just obsolete.

**Comment by Jeltje** [comment]
... but there is a bigger problem, because this is what happens next:

`cbScanpy -e filtered_gene_bc_matrices/hg19/matrix.mtx -o myscanpyout -n pbmc3k`
```
Traceback (most recent call last):
  File "/home/jeltjessh/venvs/cellBrowser/bin/cbScanpy", line 11, in <module>
    sys.exit(cbScanpyCli())
  File "/home/jeltjessh/venvs/cellBrowser/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2950, in cbScanpyCli
    if options.init:
AttributeError: 'Values' object has no attribute 'init'
```

**Comment by maximilianh** [comment]
yeah yeah, sorry, I know just committting here, I got the same error a few
hours ago...

**Comment by maximilianh** [comment]
Seems to work now.

Try:

pip install --ugprade cellbrowser

**Comment by Jeltje** [comment]
It does... until:
```
Performing Louvain Clustering, using 20 PCs and 5 neighbors
  File "/home/jeltjessh/venvs/cellBrowser/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2976, in cbScanpyCli
    adata = cbScanpy(matrixFname, confFname, figDir, logFname)
  File "/home/jeltjessh/venvs/cellBrowser/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2895, in cbScanpy
    sc.tl.louvain(adata, resolution=res)
  File "/home/jeltjessh/venvs/cellBrowser/lib/python3.6/site-packages/scanpy/tools/louvain.py", line 103, in louvain
    g = utils.get_igraph_from_adjacency(adjacency, directed=directed)
  File "/home/jeltjessh/venvs/cellBrowser/lib/python3.6/site-packages/scanpy/utils.py", line 304, in get_igraph_from_adjacency
    import igraph as ig
  File "/home/jeltjessh/venvs/cellBrowser/lib/python3.6/site-packages/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
> /home/jeltjessh/venvs/cellBrowser/lib/python3.6/site-packages/igraph/__init__.py(34)<module>()
-> from igraph._igraph import *
```
I did `pip install scanpy python-igraph louvain` as suggested elsewhere
```
pip list | grep igraph
python-igraph    0.7.1.post6
```

**Comment by Jeltje** [comment]
```
(cellBrowser) jeltjessh@svr-cellranger-1:pbmc3k>which pip2
/usr/local/bin/pip2
(cellBrowser) jeltjessh@svr-cellranger-1:pbmc3k> which pip
/home/jeltjessh/venvs/cellBrowser/bin/pip
```
As you can see, I'm doing this in a (python 3, I checked) virtualenv. I used pip to install, not pip2

**Comment by Jeltje** [comment]
Have you considered providing a Dockerfile (or image) with all the right bits?

**Comment by maximilianh** [comment]
so we're really debugging the scanpy installation here now... ok...

i wonder what happens when you start python and do

import igraph

**Comment by maximilianh** [comment]
I could easily do this, but I think it's not my job to package other
people's packages...

**Comment by maximilianh** [comment]
Also, no one that I work with can run docker images on their machines.
We're not root. Singularity would work, maybe.

**Comment by maximilianh** [comment]
Hey, you can install igraph through conda!

https://anaconda.org/conda-forge/python-igraph

**Comment by maximilianh** [comment]
quick update: I'm working on cbSeurat, which uses R and Seurat for the analysis, instead of Scanpy. It's slower, but trivial to install, so hopefully this will solve your problem.

**Comment by maximilianh** [comment]
cbScanpy --init is working now. 

Also, I've added a big ton of install instructions for Scanpy and catching the python3 version problem now.

Also I've created cbSeurat.

So I think I've done as much as possible, short of packing scanpy, as I leave that to the Scanpy authors.
