### ISSUE TITLE
cbScanpy dies on PAGA

### ISSUE THREAD

**Issue by Jeltje** [maximilianh/cellBrowser#56]
This is version 0.4.23
`cbScanpy -e </path/to/my.mtx> -o ipf3_files -n ipf3`
gets 
```
Performing UMAP
Performing PHATE
Performing PAGA+ForceAtlas2
Traceback (most recent call last):
  File "/home/cellranger/anaconda3/envs/cbConda/bin/cbScanpy", line 11, in <module>
    sys.exit(cbScanpyCli())
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3425, in cbScanpyCli
    adata = cbScanpy(matrixFname, confFname, figDir, logFname)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3331, in cbScanpy
    adata.obsm["X_pagaFa"] = adata.obsm["X_draw_graph_fa"]
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/numpy/core/records.py", line 500, in __getitem__
    obj = super(recarray, self).__getitem__(indx)
ValueError: no field of name X_draw_graph_fa
```

**Comment by maximilianh** [comment]
I'm leaving this open for now until I hear back from you.

**Comment by maximilianh** [comment]
BTW I've successfully run cbScanpy using doLayouts="all" right now on pbmc_small

**Comment by maximilianh** [comment]
cbScanpy apparently worked for you now.

**Comment by Jeltje** [comment]
Looks like I can't reopen this issue, but I just pip installed 0.4.24 and still get
```
Performing PAGA+ForceAtlas2
Traceback (most recent call last):
  File "/home/cellranger/anaconda3/envs/cellBrowserConda/bin/cbScanpy", line 11, in <module>
    sys.exit(cbScanpyCli())
  File "/home/cellranger/anaconda3/envs/cellBrowserConda/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3435, in cbScanpyCli
    adata = cbScanpy(matrixFname, confFname, figDir, logFname)
  File "/home/cellranger/anaconda3/envs/cellBrowserConda/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3341, in cbScanpy
    adata.obsm["X_pagaFa"] = adata.obsm["X_draw_graph_fa"]
  File "/home/cellranger/anaconda3/envs/cellBrowserConda/lib/python3.6/site-packages/numpy/core/records.py", line 500, in __getitem__
    obj = super(recarray, self).__getitem__(indx)
ValueError: no field of name X_draw_graph_fa
```
This happens with scanpy 1.3.2 and also after `pip --upgrade scanpy` with 1.3.6

**Comment by Jeltje** [comment]
Yes cbScanpy and yes "all".
To get it to work I replaced the `recommendedLayouts` line in cellbrowser.py with one that excludes PAGA and then it runs. 
This is the full list of dependencies as printed at the top of the log:
`scanpy==1.3.6 anndata==0.6.15 numpy==1.14.0 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.0 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1`

I did pip --upgrade on all of these and ran with `doLayouts=["pagaFa"]`. Same error.
`scanpy==1.3.6 anndata==0.6.15 numpy==1.15.4 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.1 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1`

Note that the actual error comes from `numpy/core/records.py` so I thought the upgrade would help...

**Comment by maximilianh** [comment]
I still can't reproduce this, but I'm checking now if X_draw_graph_fa
really exists instead of just assuming that it exists.

The code outputs a warning if it doesn't exist and it will simply skip this
layout, instead of failing, if the name produced by scanpy does not match
what is in the current documentation.

Thanks Jeltje!
