### ISSUE TITLE
Conda install fails for 0.4.30 due to missing setup.cfg file

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#64]
The inclusion of `versioneer.py` adds an unsatisfied requirement for a setup.cfg file (with content relevant to vesioneer I presume). The file is mentioned profusely in the versioneer comments, and required for instance here:

https://github.com/maximilianh/cellBrowser/blob/master/versioneer.py#L341

Error on conda looks like:

```
Downloading https://github.com/maximilianh/cellBrowser/archive/v0.4.30.tar.gz
Success
Extracting download
source tree in: /opt/conda/conda-bld/ucsc-cell-browser_1547827379096/work
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    version=versioneer.get_version(),
  File "/opt/conda/conda-bld/ucsc-cell-browser_1547827379096/work/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
  File "/opt/conda/conda-bld/ucsc-cell-browser_1547827379096/work/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
  File "/opt/conda/conda-bld/ucsc-cell-browser_1547827379096/work/versioneer.py", line 343, in get_config_from_root
    with open(setup_cfg, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/conda-bld/ucsc-cell-browser_1547827379096/work/setup.cfg'

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 438, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 429, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2204, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1445, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 313, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 293, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/opt/conda/conda-bld/ucsc-cell-browser_1547827379096/work/conda_build.sh']' returned non-zero exit status 1.
```

**Comment by pcm32** [comment]
There are some sample setup.cfg files here: https://github.com/warner/python-versioneer/tree/master/test

...but I'm not sure what would apply for CellBrowser.

**Comment by maximilianh** [comment]
Ooops, sorry, I somehow missed this issue! I've added the setup.cfg now, 0.4.34.
Thanks!

**Comment by pcm32** [comment]
Hi @maximilianh I'm still getting this issue, I could only find 0.4.33 but not 0.4.34, could you tag it please for me? Thanks!

**Comment by maximilianh** [comment]
Oh darn, I now learned about "git push --tags", didn't know this needed an
option.

So we're at 0.4.35 now. This is now on pip. Is this OK for you?
