### ISSUE TITLE
0.4.35 fails to run for Seurat on conda install

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#67]
cbImportSeurat2 fails when run on a conda install due to the R script not being installed:

```
Fatal error: Exit code 1 ()
INFO:root:inFname: seurat.rds, outDir: output, datasetName: output
Traceback (most recent call last):
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.4.35/bin/cbImportSeurat2", line 11, in <module>
    load_entry_point('cellbrowser==0.4.35', 'console_scripts', 'cbImportSeurat2')()
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.4.35/lib/python3.6/site-packages/cellbrowser/seurat.py", line 407, in cbImportSeurat2Cli
    cbImportSeurat2(inFname, outDir, datasetName, options)
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.4.35/lib/python3.6/site-packages/cellbrowser/seurat.py", line 365, in cbImportSeurat2
    cmds = readExportScript(cmds)
  File "/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.4.35/lib/python3.6/site-packages/cellbrowser/seurat.py", line 322, in readExportScript
    for line in open(fname):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pmoreno/miniconda3/envs/__ucsc-cell-browser@0.4.35/lib/python3.6/site-packages/cellbrowser/R/ExportToCellbrowser-seurat2.R'
```

**Comment by pcm32** [comment]
I have a PR in the make for this... just a few minutes...

**Comment by maximilianh** [comment]
Ooops... I must have forgotten to add the script to setup.py...
