### ISSUE TITLE
Bugs in v4.38

### ISSUE THREAD

**Issue by Jeltje** [maximilianh/cellBrowser#73]
Seriously dude, unit testing.

`cellbrowser/convert.py`
typo in line 34: line should be line1   
```
 elif line1.startswith("Gene ID"):
        if "Cluster 1 Weight" in line:
            fieldsProCluster = 2
            fileVersion = 1
```
However, my run then dies with the error below, [presumably because](https://github.com/numpy/numpy/issues/10018) it's trying to write raw bytes to a file that's opened as 'w' instead of 'wb'.

`cbImportCellranger -i /IPF3-3/outs -o outdir --name IPF3`
```
Traceback (most recent call last):
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1254, in savetxt
    fh.write(asbytes(format % tuple(row) + newline))
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cellranger/anaconda3/envs/cbConda/bin/cbImportCellranger", line 12, in <module>
    sys.exit(cbCellrangerCli())
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/cellbrowser/convert.py", line 394, in cbCellrangerCli
    crangerToCellbrowser(options.datasetName, options.inDir, options.outDir, options.noMat)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/cellbrowser/convert.py", line 285, in crangerToCellbrowser
    matFname = importCellrangerMatrix(inDir, outDir)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/cellbrowser/convert.py", line 229, in importCellrangerMatrix
    mtxToTsvGz(matFname, geneFname, barcodeFname, outExprFname)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3707, in mtxToTsvGz
    np.savetxt(ofh, arr, "%d", "\t", "\n")
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1258, in savetxt
    % (str(X.dtype), format))
```

**Comment by maximilianh** [comment]
the line1 error is certainly stupid. Thanks!

I haven't used the cellranger V1/V2 importer in a while, now that
cellranger 3 is out. Also, as you've seen, I have to support 3-4 different
versions of their files and in general, hardly anyone here uses the
cellranger importer, as there is Loupe already. (I'm curious: why you
aren't using Loupe3?)

How could I test a cellranger importer that requires cellranger input and
output directories with unit testing? You may mean automated testing. I
could do that, but running on the big cellranger files I have is taking
forever. Do you have a very small cellranger dataset, for testing?

The last error message is very strange. With python3, I did what you
suggested, but now I'm getting an error message. I suspect that you're
using Python2, which I support, but apparently this particular piece of
code is hard to make work on both versions. I worked around it now with an
"if isPy3:..." statement but looking forward to what the numpy folks reply
in the issue that you linked to (thanks!).

I found a small-ish sample file, pbmc3k on the 10x website. A "test" now
takes a few minutes and after my changes, on python3, the importer seems to
work again. I've tested it on both Python2 and Python3.

Thanks for your bug reports!

Do you want a new pip release or are you running the github master branch?

**Comment by Jeltje** [comment]
I'm using conda (`conda install -c bioconda ucsc-cell-browser`), and it's using python3 by default. I checked this by adding a `sys.version` to `cbImportCellranger`.

I have no say over file formats and versions of software that get run, I'm the end-of-line user of data generated two levels up. It's fine if cellbrowser doesn't support those older versions (reason for me to argue for change) but then the code should just warn and quit.

Thanks for the quick response!

**Comment by maximilianh** [comment]
What? There is a conda package for the cell browser? I didn’t really
know... I guess that is Pablo’s. Wow.

Well if you use that you won’t get the bug fix now...hmm...

**Comment by Jeltje** [comment]
It says so in your documentation...! https://cellbrowser.readthedocs.io/installation.html

Anyway, I don't have the same problem when I run on the data that just came in. It did crash because it couldn't find 'hg18' which is apparently hardcoded somewhere - I'm sorry I can't find the location anymore but I changed it to GRCh38 and then it ran.

Of course I then realized it only creates the t-sne coordinates so I just ran cbScanpy with doLayouts="all"
This is the error I get from that:

```
After filtering: Data has 21808 samples/observations and 22443 genes/variables
Expression normalization, counts per cell = 10000
Finding highly variable genes: min_mean=0.012500, max_mean=3.000000, min_disp=0.500000
Traceback (most recent call last):
  File "/home/cellranger/anaconda3/envs/cbConda/bin/cbScanpy", line 12, in <module>
    sys.exit(cbScanpyCli())
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3656, in cbScanpyCli
    adata = cbScanpy(matrixFname, confFname, figDir, logFname, matrixOutFname)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3469, in cbScanpy
    filter_result = sc.pp.filter_genes_dispersion(adata.X, min_mean=minMean, max_mean=maxMean, min_disp=minDisp)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/scanpy/preprocessing/_deprecated/highly_variable_genes.py", line 127, in filter_genes_dispersion
    gen_indices = np.where(one_gene_per_bin[df['mean_bin']])[0].tolist()
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/pandas/core/series.py", line 911, in __getitem__
    return self._get_with(key)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/pandas/core/series.py", line 953, in _get_with
    return self.reindex(key)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/pandas/core/series.py", line 3734, in reindex
    return super(Series, self).reindex(index=index, **kwargs)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/pandas/core/generic.py", line 4356, in reindex
    fill_value, copy).__finalize__(self)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/pandas/core/generic.py", line 4369, in _reindex_axes
    tolerance=tolerance, method=method)
  File "/home/cellranger/anaconda3/envs/cbConda/lib/python3.6/site-packages/pandas/core/indexes/category.py", line 503, in reindex
    raise ValueError("cannot reindex with a non-unique indexer")
ValueError: cannot reindex with a non-unique indexer
```

**Comment by maximilianh** [comment]
Hm. Thanks! I forgot that I documented that. The problem is that I don't
control the conda package so I cannot update it. Maybe I should remove
documentation of the conda package...

Hmm...There is no "hg18" harcoded anywhere. Do you mean grch38? That's
specified via the -g option. Can you send me the cbScanpy command that you
ran?

The other issue is a known scanpy problem. I cannot work around it, it's
too deep within scanpy and has to do with the numpy version:
https://github.com/theislab/scanpy/issues/450
