### ISSUE TITLE
cbScanpy, no indication that name (-n) can't be quoted to include spaces

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#75]
Nothing in the usage indicates that the name provided through the -n option must not include spaces or that it can't be quoted to include spaces. The error message also isn't really explicit here either.

Example command:
`cbScanpy -e matrix.csv -o cbScanpyOut_hESC_v4 -s -n "hESC 125 day Differentiation"`

Error message:
```INFO:root:Writing cbScanpyOut_hESC_v4/markers.tsv
Traceback (most recent call last):
  File "/cluster/home/mspeir/miniconda3/bin/cbScanpy", line 10, in <module>
    sys.exit(cbScanpyCli())
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3659, in cbScanpyCli
    scanpyToCellbrowser(adata, outDir, datasetName=datasetName, skipMatrix=True)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2877, in scanpyToCellbrowser
    writeCellbrowserConf(datasetName, coordDescs, confName, args=argDict)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2669, in writeCellbrowserConf
    assert(c.isalnum() or c in ["-", "_"]) # only digits and letters are allowed in dataset names
AssertionError
```

**Comment by maximilianh** [comment]
Thanks. Extended the error message.

>
