### ISSUE TITLE
"['UMI_Count'] not in index" error in cbScanpy

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#83]
Full error message:
```
Regressing out percent_mito and number of UMIs
Traceback (most recent call last):
  File "/cluster/home/mspeir/miniconda3/bin/cbScanpy", line 10, in <module>
    sys.exit(cbScanpyCli())
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3748, in cbScanpyCli
    adata = cbScanpy(matrixFname, confFname, figDir, logFname, matrixOutFname)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3574, in cbScanpy
    sc.pp.regress_out(adata, ['UMI_Count', 'percent_mito'])
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/scanpy/preprocessing/_simple.py", line 735, in regress_out
    regressors = adata.obs[keys]
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2726, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['UMI_Count'] not in index"
```
Command:
cbScanpy -e expression.csv -o cbScanpy_interneuron_csv -s -n Interneuron_Differentiation

File:
```
/hive/users/mspeir/cellbrowserTest/hESC_125d_diff/interneuron_diff/matrix_files/An_in_vitro_model_of_human_inhibitory_interneuron_differentiation_produced_over_time.csv/expression.csv
```

Also tried the same command on a loom file and the same error popped up, so I'm not sure if it's an issue with cbScanpy or the input data.

**Comment by maximilianh** [comment]
Argh... I missed one place... thanks!

**Comment by maximilianh** [comment]
This is harder than I thought. It's possible that there are many different
ways that the adata object is setup, due to all the possible .conf settings
in scanpy.conf. At least I think I've fixed this one now and was trying
that this doesn't happen again. UMI counts are generated if they're not
present in the scanpy object. If the gene count is not present, the
regression steps and one plotting step is skipped. I haven't done enough
testing of the various scanpy options apparently. Thanks! release 0.4.57
